config/routes.rb
Rails.application.routes.draw do
  resources :racers
  root to: 'racers#index'
end

app/models/racer.rb
class Racer
  include ActiveModel::Model
  
  attr_accessor :id, :number, :first_name, :last_name, :gender, :group, :secs

  def initialize(params={})
    @id=params[:_id].nil? ? params[:id] : params[:_id].to_s
    @number = params[:number].to_i
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @gender = params[:gender]
    @group = params[:group]
    @secs = params[:secs].to_i
  end

  def save
    result = self.class.collection
               .insert_one(
                 _id: @id,
                 number: @number,
                 group: @group,
                 secs: @secs,
                 gender: @gender,
                 first_name: @first_name,
                 last_name: @last_name)
    @id = result.inserted_id
  end

  def update(params)
    # object mutation
    @number  = params[:number].to_i  
    @first_name = params[:first_name]
    @last_name = params[:last_name]
    @group = params[:group] 
    @secs = params[:secs].to_i 
    @gender = params[:gender]

    # persistence:
    params.slice!(:number, :first_name, :last_name, :group, :gender, :secs)
    _id = BSON::ObjectId(@id)
    self.class.collection.find_one_and_update({_id: _id}, params)
  end

  def destroy
     self.class.collection.delete_one({_id:  BSON::ObjectId(@id)})
  end

  # ActiveModel support
  
  def persisted?
    !@id.nil?
  end

  def created_at
    nil
  end

  def updated_at
    nil
  end
  
  # Class Methods follow
  
  def self.mongo_client
    Mongoid::Clients.default
  end

  def self.collection
    self.mongo_client[:racers]
  end
  
  def self.all(prototype={}, sort={}, skip=0, limit=nil)
    self.collection.find(prototype, @options={ limit: limit, skip: skip, sort: sort })
  end
  
  def self.find id
    _id = id.is_a?(String) ?   BSON::ObjectId(id) : id
    params = self.all({ _id: _id }).first
    if params
      Racer.new(params)      
    else
      params
    end
  end

  def self.paginate(params)
    page = (params[:page] || 1).to_i
    limit = (params[:per_page] || 30).to_i
    skip = (page - 1) * limit

    racers = []
    self.all({}).sort({'number': 1}).limit(limit).skip(skip).each do |doc|
      racers << Racer.new(doc)
    end

    total = self.all.count

    WillPaginate::Collection.create(page, limit, total) do |pager|
      pager.replace(racers)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/racers_controller.rb
class RacersController < ApplicationController
  before_action :set_racer, only: [:show, :edit, :update, :destroy]

  # GET /racers
  # GET /racers.json
  def index
    @racers = Racer.paginate(page: params[:page], per_page: params[:per_page])
  end

  # GET /racers/1
  # GET /racers/1.json
  def show
  end

  # GET /racers/new
  def new
    @racer = Racer.new
  end

  # GET /racers/1/edit
  def edit
  end

  # POST /racers
  # POST /racers.json
  def create
    @racer = Racer.new(racer_params)

    respond_to do |format|
      if @racer.save
        format.html { redirect_to @racer, notice: 'Racer was successfully created.' }
        format.json { render :show, status: :created, location: @racer }
      else
        format.html { render :new }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /racers/1
  # PATCH/PUT /racers/1.json
  def update
    respond_to do |format|
      if @racer.update(racer_params)
        format.html { redirect_to @racer, notice: 'Racer was successfully updated.' }
        format.json { render :show, status: :ok, location: @racer }
      else
        format.html { render :edit }
        format.json { render json: @racer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /racers/1
  # DELETE /racers/1.json
  def destroy
    @racer.destroy
    respond_to do |format|
      format.html { redirect_to racers_url, notice: 'Racer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racer
      @racer = Racer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racer_params
      params.require(:racer).permit(:number, :first_name, :last_name, :gender, :group, :secs)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/racers_helper.rb
module RacersHelper
  def toRacer(value)
    value.is_a?(Racer) ? value : Racer.new(value)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raceday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/racers/_form.html.erb
<%= form_for(@racer) do |f| %>
  <% if @racer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@racer.errors.count, "error") %> prohibited this racer from being saved:</h2>

      <ul>
      <% @racer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.text_field :group %>
  </div>
  <div class="field">
    <%= f.label :secs %><br>
    <%= f.number_field :secs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/racers/edit.html.erb
<h1>Editing Racer</h1>

<%= render 'form' %>

<%= link_to 'Show', @racer %> |
<%= link_to 'Back', racers_path %>

app/views/racers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Racers</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Gender</th>
      <th>Group</th>
      <th>Secs</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @racers.each do |racer| racer = toRacer(racer) %>
	<tr>
        <td><%= racer.number %></td>
        <td><%= racer.first_name %></td>
        <td><%= racer.last_name %></td>
        <td><%= racer.gender %></td>
        <td><%= racer.group %></td>
        <td><%= racer.secs %></td>
        <td><%= link_to 'Show', racer %></td>
        <td><%= link_to 'Edit', edit_racer_path(racer) %></td>
        <td><%= link_to 'Destroy', racer, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @racers %>

<br>

<%= link_to 'New Racer', new_racer_path %>

app/views/racers/new.html.erb
<h1>New Racer</h1>

<%= render 'form' %>

<%= link_to 'Back', racers_path %>

app/views/racers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @racer.number %>
</p>

<p>
  <strong>First name:</strong>
  <%= @racer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @racer.last_name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @racer.gender %>
</p>

<p>
  <strong>Group:</strong>
  <%= @racer.group %>
</p>

<p>
  <strong>Secs:</strong>
  <%= @racer.secs %>
</p>

<%= link_to 'Edit', edit_racer_path(@racer) %> |
<%= link_to 'Back', racers_path %>